* First steps in setting up a computer

(Arch Linux)

1. Install paru
   #+begin_src
   $ yay -S paru
   #+end_src
2. Install brave-bin
   https://brave.com/linux/
   #+begin_src
   $ paru -S brave-bin
   #+end_src
3. Add brave-bin to the sync chain
   1. Let the extensions install
   2. Set up the password manager
4. Set-up ssh keys in the computer.
5. Add the ssh key in github.com and gitlab.com
6. Install git
7. Clone this and the rest of the repositories
   1. Before cloning this repo, see if there are any files in your computer in the same directories as these that are going to conflict with these. If so, take a backup of those files.

      #+NAME: Set up instructions
      #+BEGIN_SRC
      cd ~
      git init
      git remote add origin git@github.com:explorer436/Dotfiles2.git
      git pull origin main --allow-unrelated-histories
      git branch -m main
      git branch main -u remotes/origin/main
      #+END_SRC
8. Clone Mainroad theme into the appropriate repos
   #+begin_src
   mkdir themes
   cd themes
   git clone git@github.com:explorer436/Mainroad.git
   #+end_src
9. Copy the .bashrc from skel and import your customizations into it.
   1. The details about how to do it are in ~.bashrc_personal~
   2. Make sure you put this line in .bashrc (or .zprofile if it is a Macbook) after copying it from skel.
      #+begin_src
      [[ -f ~/.bashrc_personal ]] && . ~/.bashrc_personal
      #+end_src
10. Install ninja build tool
11. Install sdkman and jdk
12. Install nvm and Nodejs
13. Install hugo
14. Set-up git-sync for the repositories.
15. Install jetbrains toolbox
16. Install ripgrep
17. Install Accounting tools
