* First steps in setting up a computer

1. Install brave-bin
   https://brave.com/linux/
2. Add brave-bin to the sync chain
   1. Let the extensions install
   2. Set up the password manager
   3. Change the default search engine in brave
3. Set-up ssh keys in the computer
4. Add the ssh key in github.com and gitlab.com (sudo pacman -S geany)
5. Install emacs
6. Install git
7. Clone this and the rest of the repositories
   1. Before cloning this repo, see if there are any files in your computer in the same directories as these that are going to conflict with these. If so, take a backup of those files.

      #+NAME: Set up instructions
      #+BEGIN_SRC
      cd ~
      git init
      git remote add origin git@github.com:explorer436/Dotfiles2.git
      git pull origin main --allow-unrelated-histories
      git branch -m main
      git branch main -u remotes/origin/main
      #+END_SRC
8. Go to ~SetUpRepositories.org~
   1. Run the commands to set up the necessary tools.
   2. Install the rest of the tools manually.
9. Update custom configurations
   1. Use ~meld~ to compare configurations with backups and update them.
      #+begin_src
      meld /home/explorer436/.config/i3/config /home/explorer436/.config/i3/endeavouros_config-working-copy
      #+end_src
   2. Copy custom configurations
      #+begin_src
      cp /home/explorer436/.config/variety/backup_variety.conf /home/explorer436/.config/variety/variety.conf
      #+end_src
