* Notes about org-mode and related packages

** Org mode TODO items

Set this at the beginning of the file.
#+begin_src 
#+SEQ_TODO:  TODO STARTED WAITING | DONE CANCELED
#+SEQ_TODO:  TODO(t) STARTED(s) WAITING(w) | DONE(d) CANCELED(c)

#+SEQ_TODO:  BIRTHDAYS(b) EVENTS(e) MARRIAGEANNIVERSARIES(m) | CANCELED(c)
#+end_src
If you make changes to this line, activate with Ctrl-c Ctrl-c

** Org Agenda

https://orgmode.org/manual/Agenda-Commands.html

For additional help, look at the file org-agenda.el
If you don't know where it is, you can navigate to it using "describe-function"
e.g. describe-function org-agenda-list

Use ~C-'~ to cycle through the agenda files (org-cycle-agenda-files)

** Org Agenda Scheduling tasks and setting deadlines to tasks

https://orgmode.org/manual/Agenda-Commands.html 

https://orgmode.org/manual/Deadlines-and-Scheduling.html

~C-c C-s~ to schedule

When you want to schedule an item with Ctrl-c Ctrl-s, if you want to assign a time in addition to the date, enter the date manually and enter the time after the date. e.g. 2023-02-25 8PM and the time will also be inserted in the schedule in the org file.

~C-c C-d~ to set a deadline

If you really need to do the tasks, but there’s no point in seeing it in today’s task list because you can’t do it today anyway, use C-c C-s (org-agenda-schedule) to reschedule the task. If you’re only moving it a couple of days ahead, use S-right (org-agenda-later) to move it forward, and S-left (org-agenda-earlier) if you overshoot.

** Org mode Priorities

# https://orgmode.org/manual/Priorities.html
# C-c , to assign or change priorities

** Org mode Task states

# C-c C-c to set tags
# M-x org-tags-view to look for tags

#+begin_src 
C-c C-t

Rotate the TODO state of the current item among
,-> (unmarked) -> TODO -> DONE --.
'--------------------------------'
#+end_src

** Org mode Categories

Why am I not using TODO tags on each of these items?
Because it makes the Org Agenda looks clunky.
Using "CATEGORY" seems to be a nice way to show where each of the tasks is coming from into the Org Agenda.

*** Buffer-wide categories and heading-wise categories

I sort all my TODOs into PROJECTS, and that projects get a 4 letter abbreviation as category (using #+CATEGORY: PPPP
The category is displayed in the first column of the agenda view.
Unfortunately, with the latest update of org-mode by Jan 2018, only the last category of the file is displayed, in all lines.
Do I have to adjust my org-mode settings?

~#+CATEGORY:~ PPPP is a buffer-wide setting, so it applies to the whole file (and indeed the last setting wins). If you want categories for headings, you have to use a CATEGORY property:

#+begin_src 
   * project foo
     :PROPERTIES:
     :CATEGORY: foo
     :END:
#+end_src

** Org mode Tags

#+begin_src 
#+TAGS: BOOKS(b) ARTICLES(a)
#+end_src

Ctrl-c Ctrl-q to assign/deassign tags to an item

** Org Agenda Views

Agenda Views -
First, you need to add your Org file to your Org agenda by using the command C-c [.
Then, type Meta-x org-agenda to be presented with options for different views.


Filtering/limiting agenda items
https://orgmode.org/manual/Filtering_002flimiting-agenda-items.html

** Org refiling

https://orgmode.org/manual/Refile-and-Copy.html
https://blog.aaronbieber.com/2017/03/19/organizing-notes-with-refile.html

First, we must set the value of org-refile-targets, which tells Org how to find the possible targets. Be sure to read the documentation for this variable, because there are a few ways to define targets, but for this scenario, I want to be able to move a node to any of my agenda files, and I also want to consider nodes up to three levels deep.

That’s exactly what this setting will do.

#+begin_src 
(setq org-refile-targets '((org-agenda-files :maxlevel . 3)))
#+end_src

With this set, you can trigger Refile with C-c C-w in any Org file and get a completing read of all headings up to three levels deep in all files in org-agenda-files.

If you use Helm, which you really should, you will see a very pretty hierarchical display of possible targets. You can type a filename to narrow down to headings within that file, and so on.

** Org checkboxes

   https://orgmode.org/manual/Checkboxes.html

** How to?

    How to send notifications from Org Mode planner/schedueler?
    If this works, can this be a replacement for Google Calendar?

** How to auto save an org document in markdown format?

    To do it automatically,
    install the package ~auto-org-md~ and use ~Meta x auto-org-md-mode~ to toggle the auto save to markdown functionality on and off.
    
    If you turn it on,
    after editing a file in org-mode, when you save it, a markdown version of the file is saved automatically in the same folder that the org file is in.

    Is there a way to do this without using the 'auto-org-md' package?
    This may not be necessary at all. The org files are showing up very nicely in github. So there is no need to export them as markdown files at all.

** Exporting

(After making changes to the file, use C-c C-e to launch the export command if you want to export it as a text file or into any other format).

You might want to print your notes, publish them on the web, or share them with people not using Org.
Org can convert and export documents to a variety of other formats while retaining as much structure (see Document Structure) and markup (see Markup for Rich Contents) as possible.  

Use ~Ctrl c Ctrl e~ to launch the export command and then use the options displayed to make selections.
e.g. to export as a UTF-8 plain text file, select 't' and 'u'

** Lists

       How to change the style of bullets?
       e.g. Change a star bullet list into number bullet list. Or vice versa.

       https://orgmode.org/manual/Plain-Lists.html

** Sorting todo items and items based on priority
      M-x org-sort-entries and then pick the type of entry by which you want to sort.

** Group tasks into projects

Some tasks show up again and again on your task list, and you know you need to do them, but you don’t know where to getting started. “TODO Write a book” is not a good task, because it’s just too big to do in one sitting and it doesn’t tell you what to do right now. Big tasks are often projects in disguise. Break down the projects into smaller tasks by adding sub-headings and more TODOs, and schedule those instead.

Like this:

 ** Write a book
 *** TODO Make an outline of what to write
 *** TODO Read sample query letters
 *** TODO Write a query letter

You can have as many active projects as you want projects at the same time. Each project contains small actions to be performed.

** Using Timestamps, scheduling & deadlines

+Try to avoid using timestamps in projects as much as possible. The reason is simple: unless an entry is an appointment (to the dentist for instance) or has a fixed deadline (a release scheduled with a customer), you should decide what to work on depending on the current context (among other things). This also keeps the agenda clean, free of any fake or self-imposed deadline or schedule.+

** Filtering projects & actions

    Use sparse trees - M-x org-sparse-trees

** Organize the tasks into into projects when there are more than one tasks that are related to each other

** Difference between putting a normal active timestamp on a task vs putting a SCHEDULED or DEADLINE timestamp on a task

| Normal active timestamps                                                       | SCHEDULED or DEADLINE timestamps                                                                      |
|--------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------|
| For "hard landscape" for your day                                              | These are for "tickler items" that can also be done on a different day                                |
| These tasks show up both in Org Agenda List in emacs and the exported ics file | These show up in Org Agenda List but these do not show up in exported iCal file or in Google Calendar |
